import React, { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { SEO } from '../SEO';

const StoryExamplesPage = () => {
  const { t, i18n } = useTranslation();
  const [stories, setStories] = useState([]);
  const [filteredStories, setFilteredStories] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [useMockData, setUseMockData] = useState(false); // Siempre intentamos Firebase primero
  const [filters, setFilters] = useState({
    age: 'all',
    language: 'all',
    level: 'all'
  });
  const [diagnosticResults, setDiagnosticResults] = useState(null);
  const [runningDiagnostic, setRunningDiagnostic] = useState(false);
  
  // Ejecutar verificación de permisos al inicio
  useEffect(() => {
    const runDiagnostics = async () => {
      try {
        console.log("Ejecutando diagnóstico de permisos de Firebase Storage...");
        await checkStoragePermissions();
      } catch (error) {
        console.error("Error ejecutando diagnóstico:", error);
      }
    };
    
    runDiagnostics();
  }, []);

  // Función para ejecutar diagnóstico de CORS manualmente
  const handleRunDiagnostic = async () => {
    try {
      setRunningDiagnostic(true);
      console.log("Ejecutando diagnóstico manual de Firebase Storage...");
      const results = await checkStoragePermissions();
      setDiagnosticResults(results);
      console.log("Resultados del diagnóstico:", results);
    } catch (error) {
      console.error("Error en diagnóstico manual:", error);
      setDiagnosticResults({ error: error.message });
    } finally {
      setRunningDiagnostic(false);
    }
  };

  return (
    <div className="story-examples-page">
      <SEO 
        title={i18n.language === 'es' ? 
          'Ejemplos de Cuentos Personalizados - AudioGretel' : 
          'Personalized Story Examples - AudioGretel'}
        description={i18n.language === 'es' ? 
          'Explora nuestra colección de cuentos de ejemplo generados por AudioGretel para todas las edades y niveles de idioma.' : 
          'Explore our collection of example stories generated by AudioGretel for all ages and language levels.'}
        keywords={['ejemplos de cuentos', 'cuentos para niños', 'cuentos en español', 'cuentos en inglés']}
        lang={i18n.language}
      />
      
      <div className="page-header">
        <h1>{t('storyExamples.title')}</h1>
        <p>{t('storyExamples.description')}</p>
        {useMockData && (
          <div className="alert alert-warning">
            <strong>Note:</strong> Using sample data. To see real stories, please update your Firebase security rules as described in the README.
          </div>
        )}
        
        {/* Botón de diagnóstico para desarrolladores */}
        <div className="diagnostic-tools">
          <button 
            onClick={handleRunDiagnostic} 
            disabled={runningDiagnostic}
            className="btn btn-outline-secondary btn-sm"
          >
            {runningDiagnostic ? 'Ejecutando diagnóstico...' : 'Diagnosticar conexión a Firebase'}
          </button>
          
          {diagnosticResults && (
            <div className="diagnostic-results mt-2">
              <h6>Resultados del diagnóstico:</h6>
              <pre className="diagnostic-code">
                {JSON.stringify(diagnosticResults, null, 2)}
              </pre>
            </div>
          )}
        </div>
      </div>

      {/* ... existing code ... */}
    </div>
  );
};

const StoryCard = ({ story, t, useMockData = false }) => {
  console.log(`Renderizando StoryCard para: ${story.id}, useMockData: ${useMockData}`);
  
  const [textUrl, setTextUrl] = useState('');
  const [audioUrl, setAudioUrl] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [storyContent, setStoryContent] = useState('');
  const [showAudio, setShowAudio] = useState(false);
  const [usingMockContent, setUsingMockContent] = useState(true); // Por defecto asumimos que usaremos mock
  const [isRetrying, setIsRetrying] = useState(false);

  // Use different mock stories for each story ID
  const getMockStoryContent = () => {
    console.log(`Obteniendo contenido mock para: ${story.id}`);
    switch(story.id) {
      case 'dragon-no-volar':
        return `${story.title}

Había una vez un pequeño dragón llamado Puff que vivía en las montañas azules. A diferencia de otros dragones, Puff tenía un problema: no podía volar. Sus alas eran demasiado pequeñas y por más que lo intentaba, no lograba elevarse del suelo.

Todos los días, Puff observaba a los otros dragones volar alto en el cielo, haciendo piruetas y jugando entre las nubes. Se sentía muy triste porque quería jugar con ellos, pero no podía.

Un día, mientras caminaba por el bosque, Puff encontró a una pequeña niña que estaba perdida. La niña lloraba porque no podía encontrar el camino a su casa.

"No llores", le dijo Puff. "Yo te ayudaré a encontrar tu casa".

La niña se sorprendió al ver un dragón tan amable. Juntos caminaron por el bosque, y Puff usó su excelente sentido del olfato para seguir el rastro hasta la aldea donde vivía la niña.

Cuando llegaron, todos los habitantes del pueblo estaban asombrados. ¡Un dragón había ayudado a la niña! Estaban tan agradecidos que organizaron una gran fiesta para Puff.

Durante la fiesta, Puff se dio cuenta de algo importante: aunque no podía volar como los otros dragones, tenía otras habilidades especiales. Era amable, valiente y tenía un gran sentido del olfato que le permitía ayudar a los demás.

Desde ese día, Puff ya no se sintió triste por no poder volar. Había encontrado su propio camino para ser feliz y ayudar a los demás. Y así, el dragón que no podía volar se convirtió en el dragón más querido de todas las montañas azules.

Fin`;
      case 'princesa-valiente':
        return `${story.title}

Había una vez una princesa llamada Elena que vivía en un reino lejano. A diferencia de otras princesas, a Elena no le gustaban los vestidos elegantes ni las fiestas del palacio. Ella prefería explorar el bosque, trepar a los árboles y aprender a usar la espada.

El rey y la reina estaban preocupados por su hija. "Una princesa debe comportarse como tal", le decían. Pero Elena tenía otros planes.

Un día, un terrible dragón llegó al reino y comenzó a aterrorizar a los aldeanos. El rey envió a sus mejores caballeros para derrotar a la bestia, pero todos fallaron.

"Yo puedo derrotar al dragón", dijo Elena a su padre. El rey se rió. "Eres solo una niña", respondió. Pero Elena estaba decidida.

Esa noche, tomó la armadura de un caballero, una espada y partió hacia la cueva del dragón. Cuando llegó, no atacó de inmediato. En cambio, observó al dragón y notó algo extraño: tenía una espina clavada en su pata que le causaba dolor.

Con mucho cuidado, Elena se acercó al dragón. "No te haré daño", le dijo. "Quiero ayudarte". El dragón, aunque asustado, permitió que Elena le quitara la espina.

El dragón estaba tan agradecido que prometió no volver a molestar al reino. Elena regresó al castillo montada sobre el lomo del dragón, sorprendiendo a todos.

El rey y la reina finalmente entendieron que su hija era valiente y sabia a su manera. Desde ese día, Elena fue conocida como la princesa valiente, y cuando creció, se convirtió en la mejor gobernante que el reino había tenido jamás.

Fin`;
      default:
        // For any other story ID, use a generic mock story
        return `${story.title}

Esta es una historia de ejemplo para ${story.title}.

El contenido real se cargará desde Firebase cuando esté disponible.

Fin`;
    }
  };

  // Get the appropriate mock story content based on the story ID
  const MOCK_STORY = getMockStoryContent();
  
  // Función para cargar el contenido
  const loadContent = async () => {
    try {
      setLoading(true);
      
      // Establecer contenido mock como fallback
      setTextUrl('#');
      setAudioUrl('#');
      setStoryContent(MOCK_STORY);
      setUsingMockContent(true);
      console.log(`[${story.id}] Contenido mock establecido`);
      
      // Solo intentar cargar audio desde Firebase, el texto siempre será mock
      if (story.audioPath) {
        try {
          console.log(`[${story.id}] Cargando audio desde: ${story.audioPath}`);
          const url = await getStoryAudioUrl(story.audioPath);
          
          if (url) {
            console.log(`[${story.id}] ✓ Audio cargado correctamente: ${url}`);
            setAudioUrl(url);
          } else {
            console.warn(`[${story.id}] No se pudo obtener URL de audio real`);
          }
        } catch (audioError) {
          console.error(`[${story.id}] Error al cargar audio:`, audioError);
        }
      } else {
        console.warn(`[${story.id}] No hay ruta de audio definida`);
      }
      
      setLoading(false);
      setError(null);
    } catch (error) {
      console.error(`[${story.id}] Error al cargar contenido:`, error);
      setError(error);
      setLoading(false);
    }
  };
  
  // ... existing code ...
};

export default StoryExamplesPage; 